FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install minio python-dotenv pandas

COPY src/ingestion/ ./src/ingestion/

COPY src/producer/ ./src/producer/

COPY data/raw/ ./data/raw/
COPY .env .

CMD ["python", "src/ingestion/init_minio.py"]